[[network]]

name 		= "quarre_audio"
protocol 	= "oscquery"
udp_port	= 1234
ws_port		= 5678

[[audio]]

nchannels	= 8
expose		= true
netname		= "audio-backend"
active		= true
srate		= 44100
block		= 512

[[unit]]

type 		= "vst_hdl"
plugin 		= "Kaivo"
expose 		= true
netname 	= "kaivo_1"

[[unit]]

type 		= "vst_hdl"
plugin		= "Absynth 5"
expose		= true
netname 	= "absynth"
active		= false
level		= 0.5

[[unit]]

type		= "oneshots"
sfpath		= "/audio/soundfiles/test.wav"
level 		= 0.5
expose		= true
netname		= "os_test"
active		= false
out_chn		= 5

[[aux_track]]

name 		= "verb_aux"

[[aux_track.receiver]]

type		= "vst_hdl"
plugin		= "Altiverb 7"
expose		= false
program		= "TubeWorks"
active		= true
level		= 1.0

[[aux_track.sender]]

id			= "kaivo_1"
db_level	= -6.0

[[track]]

netname		= "track_1"
expose		= true

[[track.child]]

type 		= "oneshots"
sfpath		= "/audio/soundfiles/test.wav"
db_level	= -6.0
active 		= false

[[track.child]]

type		= "rooms"
n_in		= 1
n_out		= 8

[[unit]]

type		= "fields"
sfpath		= "/audio/soundfiles/test.wav"
level 		= 0.5
expose		= true
netname		= "fields_test"
active		= false
